gestorpsi/ehr/urls.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from gestorpsi.authentication.views import login_check
from gestorpsi.ehr.views import *

urlpatterns = patterns('',
    # Session's URL
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/$', login_check(session_list)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/(?P<session_id>\d+)/item/$', login_check(session_item_html)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/add/$', login_check(session_form)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/(?P<session_id>\d+)/$', login_check(session_form)),

    # Diagnosis's URL
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/$', login_check(diagnosis_list)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/(?P<diagnosis_id>\d+)/item/$', login_check(diagnosis_item_html)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/add/$', login_check(diagnosis_form)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/(?P<diagnosis_id>\d+)/$', login_check(diagnosis_form)),
    
    # Demand's URL
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/$', login_check(demand_list)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/(?P<demand_id>\d+)/item/$', login_check(demand_item_html)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/add/$', login_check(demand_form)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/(?P<demand_id>\d+)/$', login_check(demand_form)),
)

gestorpsi/gcm/urls.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.conf.urls.defaults import url, patterns
from django.views.generic.simple import direct_to_template
from django.contrib.auth.decorators import login_required

from gestorpsi.gcm.views.views import org_object_list

urlpatterns = patterns('',
    # use by admin section
    url(r'^$', login_required( direct_to_template ), {'template':'gcm/index.html'}, name='gcm-index'),
    url(r'gcm/org/$', login_required( org_object_list ), name='org-list'),
)

gestorpsi/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
#from gestorpsi.authentication.forms import RegistrationForm
from gestorpsi.authentication.models import Profile
from gestorpsi.frontend.views import start as frontend_start
from django.contrib.auth.decorators import login_required
from gestorpsi.authentication.views import gestorpsi_login

from gestorpsi.settings import MEDIA_ROOT

admin.autodiscover()

urlpatterns = patterns('',
    # url
    (r'^$', login_required(frontend_start)),
    url(r'^accounts/login/$', 'gestorpsi.authentication.views.gestorpsi_login', {'template_name': 'registration/login.html'}, name='auth_login'),

    # registration org form
    url(r'^accounts/register/$', 'gestorpsi.authentication.views.register', name='registration-register'),
    url(r'^accounts/complete/$', 'gestorpsi.authentication.views.complete', name='registration-complete'),

    # user custom admin for GCM
    url(r'^admin/gcm/$', 'gestorpsi.gcm.views.views.org_object_list', name='gcm-index'),

    # include
    (r'^accounts/', include('gestorpsi.authentication.urls')),
    (r'^accounts/', include('registration.urls')), # logout
    (r'^admin/', include(admin.site.urls)),
    (r'^contact/', include('gestorpsi.contact.urls')),
    (r'^place/', include('gestorpsi.place.urls')),
    (r'^careprofessional/', include('gestorpsi.careprofessional.urls')),
    (r'^client/', include('gestorpsi.client.urls')),
    (r'^client/', include('gestorpsi.demographic.urls')),
    (r'^client/', include('gestorpsi.ehr.urls')),
    #(r'^client/', include('gestorpsi.socioeconomic.urls')),
    (r'^admission/', include('gestorpsi.admission.urls')),
    (r'^referral/', include('gestorpsi.referral.urls')),
    (r'^employee/', include('gestorpsi.employee.urls')),
    (r'^person/', include('gestorpsi.person.urls')),
    (r'^address/', include('gestorpsi.address.urls')),
    (r'^service/', include('gestorpsi.service.urls')),
    (r'^device/', include('gestorpsi.device.urls')),
    (r'^organization/', include('gestorpsi.organization.urls')),
    (r'^upload/', include('gestorpsi.upload.urls')),
    (r'^user/', include('gestorpsi.users.urls')),
    (r'^schedule/', include('gestorpsi.schedule.urls')),
    (r'^report/', include('gestorpsi.report.urls')),
    (r'^support/', include('gestorpsi.support.urls')),
    (r'^frontend/', include('gestorpsi.frontend.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'^profile/', include('gestorpsi.profile.urls')),
    (r'^util/', include('gestorpsi.util.urls')),
    (r'^chaining/', include('smart_selects.urls')),
    (r'^sentry/', include('sentry.web.urls')),
    (r'^gcm/', include('gestorpsi.gcm.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

gestorpsi/util/urls.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from gestorpsi.util.views import cnae, ocupation

urlpatterns = patterns('',
    (r'^cnae/$', login_required(cnae)), 
    (r'^ocupation/$', login_required(ocupation)), 
)

gestorpsi/address/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

import reversion
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from gestorpsi.util.uuid_field import UuidField

class Country(models.Model):
    name = models.CharField(max_length=50)
    nationality = models.CharField(max_length=50)
    def __unicode__(self):
        return u"%s" % self.name
    class Meta:
        ordering = ['name']

class State(models.Model):
    name = models.CharField(max_length=50)
    shortName = models.CharField(max_length=2)
    country = models.ForeignKey(Country)
    def __unicode__(self):
        return u"%s" % self.name
    class Meta:
        ordering = ['name']

class City(models.Model):
    ibge_code = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    state = models.ForeignKey(State)
    def __unicode__(self):
        return u"%s" % (self.name)
    class Meta:
        ordering = ['name']

class AddressType(models.Model):
    description = models.CharField(max_length=20)
    weight = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return u"%s" % self.description

    class Meta:
        ordering = ['weight']

class Address(models.Model):
    # Brazil Address
    id= UuidField( primary_key= True )
    addressPrefix = models.CharField(max_length=10)
    addressLine1 = models.CharField(max_length=50, blank=True)
    addressLine2 = models.CharField(max_length=50, blank=True)
    addressNumber = models.CharField(max_length=10, blank=True)
    neighborhood = models.CharField(max_length=30, blank=True)
    zipCode = models.CharField(max_length=10, blank=True)
    addressType = models.ForeignKey(AddressType)
    city = models.ForeignKey(City, null=True)
    # Foreign Address
    foreignCountry = models.ForeignKey(Country, null=True)
    foreignState   = models.CharField(max_length=20, blank=True)
    foreignCity    = models.CharField(max_length=50, blank=True)
    # Generic Relationship
    content_type = models.ForeignKey(ContentType)
    object_id = models.CharField(max_length=36)
    content_object = generic.GenericForeignKey()
    
    def __cmp__(self, other):
        if (self.addressPrefix == other.addressPrefix) and \
           (self.addressLine1 == other.addressLine1) and \
           (self.addressLine2 == other.addressLine2) and \
           (self.addressNumber == other.addressNumber) and \
           (self.neighborhood == other.neighborhood) and \
           (self.zipCode == other.zipCode) and \
           (self.addressType == other.addressType) and \
           (self.city == other.city) and \
           (self.foreignCountry == other.foreignCountry) and \
           (self.foreignState == other.foreignState) and \
           (self.foreignCity == other.foreignCity):
            return 0
        else:
            return 1    
    
    def __unicode__(self):
        return u"%s %s %s %s<br />%s %s %s %s %s (%s)" % (\
            self.addressPrefix, self.addressLine1, self.addressNumber, self.addressLine2, \
            self.zipCode, self.neighborhood, self.city, '' if not hasattr(self.city, 'state') else self.city.state.shortName, '' if not hasattr(self.city, 'state') else self.city.state.country, self.addressType\
        )
    
    def __empty__(self):
        return ''
    area = property(__empty__)

    def revision(self):
        return reversion.get_for_object(self).order_by('-revision__date_created').latest('revision__date_created').revision

reversion.register(Address)

gestorpsi/cbo/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.db import models

class Occupation(models.Model):
    """
    This class represents an occupation according to http://www.mte.gov.br
    @author: GestorPsi
    @version: 1.0
    """
    id = models.IntegerField(primary_key=True)
    cbo_code = models.CharField(max_length=999)
    title = models.CharField(max_length=999)

    def __unicode__(self):
        return u"%s" % self.title

class Synonyms(models.Model):
    """
    This class represents a synonyms that refers to an occupation
    @author: GestorPsi
    @version: 1.0
    """
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=999)
    occupation = models.ForeignKey(Occupation)

    def __unicode__(self):
        return u"%s" % self.title

gestorpsi/device/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

import reversion
from django.db import models
from django.utils.translation import ugettext as _
from gestorpsi.organization.models import Organization
from gestorpsi.place.models import Place, Room
from gestorpsi.careprofessional.models import Profession
from gestorpsi.util.uuid_field import UuidField

DURABILITY_TYPE= ( ('1',_('CONSUMABLE')), ('2', _('DURABLE')) )
"""
Devices are classified by their durability, thus this variable represents
the two kinds of durability type that are used to classify them.
"""

MOBILITY_TYPE= ( ( '1', _('FIX') ), ( '2', _('MOBILE') ) )
"""
Similarly, devices are also classified by their mobility, thus this variable represents
the two kinds of mobility type that are used to classify them.
"""

class DeviceDetailsManager(models.Manager):
    def mobile(self):
        return super(DeviceDetailsManager, self).get_query_set().filter(mobility__exact='2')

    def fix(self):
        return super(DeviceDetailsManager, self).get_query_set().filter(mobility__exact='1')

    def active(self, organization):
        return super(DeviceDetailsManager, self).get_query_set().filter(active = True, device__organization = organization).order_by('model')

    def deactive(self, organization):
        return super(DeviceDetailsManager, self).get_query_set().filter(active = False, device__organization = organization).order_by('model')

class Device(models.Model):
    """
    The class C{Device} is used to represent devices in the context of the GestorPsi project. Using this class,
    the user is able to query the quantity of some kind of device currently available as well as the number of existing
    devices of the underlying type.
    @version: 1.0
    """
    id = UuidField(primary_key=True)
    description = models.CharField( max_length = 80 )
    organization = models.ForeignKey(Organization, null=True)

    def get_all_device_details(self):
        return DeviceDetails.objects.filter( device__id= self.id )

    def __unicode__(self):
       return u"%s" % ( self.description )

    def revision(self):
        return reversion.get_for_object(self).order_by('-revision__date_created').latest('revision__date_created').revision

    class Meta:
        ordering = ['description']
        permissions = (
            ("device_add", "Can add devices"),
            ("device_change", "Can change devices"),
            ("device_list", "Can list devices"),
            ("device_write", "Can write devices"),
        )



class DeviceDetails(models.Model):
    """
    Instances of this class holds details about devices. For example, brand, comments, and so forth.
    @version: 1.0
    @see: Device
    """
    id = UuidField(primary_key=True)
    brand = models.CharField( max_length=80 )
    model = models.CharField( max_length=80 )
    part_number = models.CharField( max_length=45 )
    lendable = models.BooleanField( default=True )
    comments = models.CharField( max_length=200 )
    durability = models.CharField( max_length=1, choices=DURABILITY_TYPE )
    prof_restriction = models.ForeignKey(Profession, null=True)
    mobility = models.CharField( max_length=1, choices=MOBILITY_TYPE )
    place = models.ForeignKey(Place, null=True)
    room = models.ForeignKey(Room, null=True)
    device = models.ForeignKey(Device)
    active = models.BooleanField(default=True)

    objects = DeviceDetailsManager()

    class Meta:
        ordering = ['brand']
        permissions = (
            ("devicedetails_write", "Can write device details"),
        )

    def __unicode__(self):
        device_type = _("Type")
        device_model = _("Model")
        device_part_number = _("Part number")
        return u"%s: %s - %s: %s - %s: %s" % \
                 (device_type, self.device.description, device_model, self.model, device_part_number, self.part_number)

    def revision(self):
        return reversion.get_for_object(self).order_by('-revision__date_created').latest('revision__date_created').revision

reversion.register(DeviceDetails, follow=['device'])
reversion.register(Device)

gestorpsi/templates/device/device_form.html
{% extends "core/main.html" %}

{% comment %}

Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

{% endcomment %}

{% load i18n %}

{% block menu_myoffice %}active{% endblock %}

{% block vertical_menu %} - {% trans "Equipments" %}{% endblock %}

{% block submenu %}
    <ul>
        <li><a class="first" href="/device/">{% trans "all" %}</a></li>
        <li><a class="{% if not object.id %}active{% endif %}" href="/device/add/">{% trans "add" %}</a></li>
        <li><a href="/device/type/">{% trans "types" %}</a></li>
        {% if object.id %}<li><a class="active">{{ object.model }}</a></li>{% endif %}
        <li><a class="{% if deactive %} active {% endif %}" href="/device/deactive/">{% trans "all Deactives" %}</a></li>
        
    </ul>
{% endblock %}


{% block core %}

{% if object.id %}
	<h2 class="title_device title">{{ object.model }}</h2>
	<p class="description">{{ object.device.description }}<br></p>
{% else %}
	<h2 class="title_device title">{% trans "Adding Equipments" %}</h2>
	<p class="description">{% trans "Inform the equipment details then click on Save button" %}</p>
{% endif %}


<form action="/device/{% if object.id %}{{ object.id }}/{% endif %}save/" method="post" class="form_device {% if object.id %} edit_device {%else%} new_device_form {% endif %}" id="form_device">	
<div class="main_area">

<!-- <a href="" id="help">&nbsp;</a> -->

	<div id="device_form">

		<!-- device -->
	
		<fieldset id="fieldset_device">
		<legend>{% trans "Devices" %}</legend>
			
			<label>{% trans "Select Device Type or" %} <a class="form_mini" display="device_mini">{% trans "add a new one" %}</a><br />
			<select name="select_device" class="select giant asm">
				{% for l in device_type %}
				<option value="{{ l.id }}"{% ifequal object.device.id l.id %} selected{% endifequal %}>{{ l.description }}</option>
				{% endfor %}
			</select>
			</label>
		</fieldset>	
	

	<!-- identification -->
	
	<fieldset id="fieldset_device_identification">
		<legend>{% trans "Adding equipment details" %}</legend>
		
                        <label>{% trans "Model" %}<br />
                        <input type="text" maxlength="80" name="model" class="giant" value="{{ object.model }}" id="model" />
                        </label>

			<label>{% trans "Brand" %}<br />
			<input type="text" maxlength="80" name="brand" class="giant tabtitle" value="{{ object.brand }}" id="brand" />
			</label>
			
			<label>{% trans "Part number" %}<br />
			<input type="text" maxlength="45" name="part_number" class="giant" value="{{ object.part_number }}" id="part_number" />
			</label>
			
			<label>{% trans "Comments" %}<br />
			<textarea name="comments" class="giant" value="{{ object.comments }}" id="comments">{{ object.comments }}</textarea>
			</label>
			
				
	</fieldset>
	
	
	<!--  lendable checkbox -->
     
     <fieldset id="fieldset_lendable_status">
		<legend>{% trans "Lendable Status" %}</legend>
			<label>
			<input type="checkbox" name="lendable" id="id_lendable" {% if object.lendable %} checked{% endif %} /><label>{% trans "Lendable?" %}
			</label>
	</fieldset>
	
	
  
	
    <!--  durability  --> 
    
    <fieldset id="fieldset_durability_type">
		<legend>{% trans "Durability" %}</legend>
			<label>{% trans "Type" %}<br />
			<select name="select_durability_type" class="extramedium">
				<option value="1"{% ifequal object.durability '1' %} selected{% endifequal %}>{% trans "Consumable" %}</option>
				<option value="2"{% ifequal object.durability '2' %} selected{% endifequal %}>{% trans "Durable" %}</option
			></select>
			</label>	
	</fieldset>
	
	
    
    <!--  use  --> 

    <fieldset id="fieldset_use_type">
		<legend>{% trans "Restriction" %}</legend>
		<label>{% trans "Type" %}<br />
			<select name="select_restriction_type" class="device_restriction extramedium">
				<option value="1">{% trans "Not restrict" %}</option>
				<option value="2"{% if object.prof_restriction %} selected{% endif %}>{% trans "Restrict" %}</option>
			</select>
		</label>
		
		<!--  profission  -->
		<label class="device_restriction" {% if object.prof_restriction %} style="display: block;" {% else %} style="display: none;" {% endif %} >{% trans "Profissional Area" %}<br />
		    <select name="professional_area" class="extramedium">
			    {% for l in PROFESSIONAL_AREAS %}
				    <option value="{{ l.id }}"{% ifequal object.prof_restriction.id l.id %} selected{% endifequal %}>{{ l }}</option>
			    {% endfor %}
		    </select>
		</label>
	</fieldset>

    <!--  mobility --> 
    
    <fieldset id="fieldset_mobility_type">
		<legend>{% trans "Mobility" %}</legend>
		<label>{% trans "Type" %}<br />
			<select name="select_mobility_type" class="device_mobility extramedium">
				<option value="2"{% ifequal object.mobility '2' %} selected{% endifequal %}>{% trans "Mobile" %}</option>
				<option value="1"{% ifequal object.mobility '1' %} selected{% endifequal %}>{% trans "Fix" %}</option>
			</select>
		</label>

		<!--  place  -->
		<label class="device_place clear">{% trans "Place" %}<br />
			<select name="place_associated" class="extramedium device_place">
                <option value="">------------</option>
				{% for p in places %}
					<option value="{{ p.id }}"{% ifequal object.place_id p.id %} selected{% endifequal %}{% if not p.room_set.all %} no_room="True"{% ifequal object.mobility '1' %} disabled{% endifequal %}{% endif %}>{{ p.label }}</option>
				{% endfor %}
			</select>

		<!--  room  -->
		<label class="device_room"{% ifnotequal object.mobility '1' %} style="display:none;"{% endifnotequal %}>{% trans "Room" %}<br />
			<select name="room_associated" class="extramedium device_room">
                <option value="">------------</option>
				{% for p in places %}
					{% for r in p.room_set.all %}
						<option class="place_{{ p.id }}" value="{{ r.id }}"{% if object.place_id %}{% ifnotequal p.id object.place_id %} style="display:none;"{% endifnotequal %}{% endif %}{% if not forloop.parentloop.first and not object.id %} style="display:none;"{% endif %}{% ifequal object.room_id r.id %} selected{% endifequal %}>{{ r }}</option>
					{% endfor %}
				{% endfor %}
			</select>
		</label>		
	</fieldset>
    <br>
	</div>
</div>

<div id="sidebar" class="sidebar">
    {% if perms.device.device_write %}
    	<div class="bg_blue">
        	<input type="hidden" name="place" value="{{ object.id }}" />
            {% include "tags/save.html" %}
        </div>

        {% if object.id %}
            {% include "tags/device_sidebar.html" %}
        {% endif %}

    {% endif %}
</div>

</form>

{% include "tags/device_mini.html" %}

{% endblock %}

gestorpsi/templates/device/device_list.html
{% extends "core/main.html" %}

{% comment %}

Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

{% endcomment %}

{% load i18n %}

{% block menu_myoffice %}active{% endblock %}

{% block vertical_menu %} - {% trans "Equipments" %}{% endblock %}

{% block submenu %}
    <ul>
        <li><a class="first {% if not deactive %} active {% endif %}" href="/device/">{% trans "all" %}</a></li>
        <li><a href="/device/add/">{% trans "add" %}</a></li>
        <li><a href="/device/type/">{% trans "types" %}</a></li>
        <li><a class="{% if deactive %} active {% endif %}" href="/device/deactive/">{% trans "all Deactive" %}</a></li>
    </ul>
{% endblock %}

{% block core %}

<div class="registers_available">
        <h2 class="title_device">{% trans "All Devices" %}</h2>
        <p class="description">{% trans "Displaying" %} <a href="/device/" display="list"><span id="object_length"></span> {% trans "device(s)" %}</a>. {% trans "Page" %} <b></b> {% trans "of" %} <b></b></p>

        <div class="main_area contact">

            <div id="search_header" class="device_search {% if deactive %} deactive {% else %} active {% endif %}">
                {% include "tags/search_header.html" %}
            </div>

            <div id="msg_area" class="alert no_registers_available hidden">
                {% trans "There is no registers available." %}<br /><br />{% trans "Click" %} <a href="/device/add/" class="fastmenu notajax" sub_menu="sub_devices" display="form">{% trans "here" %}</a> {% trans "if you want to add a new one." %}
            </div>
                <table id="search_results" class="zebra newtab devices" border="0" cellspacing="0" cellpadding="0">
                <thead> 
                        <tr> 
                        <th></th> 
                        <th></th> 
                        </tr> 
                </thead>
                <tbody>               
                <script>
                    {% if deactive %}
                        updateDevice('/device/page1/deactive/', true);
                    {% else %}
                        updateDevice('/device/page1');
                    {% endif %}
                </script>
                </tbody>
                </table>
                {% include "tags/paginator.html" %}
        </div>
</div>
{% endblock %}