gestorpsi/ehr/urls.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from gestorpsi.authentication.views import login_check
from gestorpsi.ehr.views import *

urlpatterns = patterns('',
    # Session's URL
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/$', login_check(session_list)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/(?P<session_id>\d+)/item/$', login_check(session_item_html)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/add/$', login_check(session_form)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/(?P<session_id>\d+)/$', login_check(session_form)),

    # Diagnosis's URL
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/$', login_check(diagnosis_list)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/(?P<diagnosis_id>\d+)/item/$', login_check(diagnosis_item_html)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/add/$', login_check(diagnosis_form)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/(?P<diagnosis_id>\d+)/$', login_check(diagnosis_form)),
    
    # Demand's URL
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/$', login_check(demand_list)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/(?P<demand_id>\d+)/item/$', login_check(demand_item_html)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/add/$', login_check(demand_form)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/(?P<demand_id>\d+)/$', login_check(demand_form)),
)

gestorpsi/gcm/urls.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.conf.urls.defaults import url, patterns
from django.views.generic.simple import direct_to_template
from django.contrib.auth.decorators import login_required

from gestorpsi.gcm.views.views import org_object_list

urlpatterns = patterns('',
    # use by admin section
    url(r'^$', login_required( direct_to_template ), {'template':'gcm/index.html'}, name='gcm-index'),
    url(r'gcm/org/$', login_required( org_object_list ), name='org-list'),
)

gestorpsi/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
#from gestorpsi.authentication.forms import RegistrationForm
from gestorpsi.authentication.models import Profile
from gestorpsi.frontend.views import start as frontend_start
from django.contrib.auth.decorators import login_required
from gestorpsi.authentication.views import gestorpsi_login

from gestorpsi.settings import MEDIA_ROOT

admin.autodiscover()

urlpatterns = patterns('',
    # url
    (r'^$', login_required(frontend_start)),
    url(r'^accounts/login/$', 'gestorpsi.authentication.views.gestorpsi_login', {'template_name': 'registration/login.html'}, name='auth_login'),

    # registration org form
    url(r'^accounts/register/$', 'gestorpsi.authentication.views.register', name='registration-register'),
    url(r'^accounts/complete/$', 'gestorpsi.authentication.views.complete', name='registration-complete'),

    # user custom admin for GCM
    url(r'^admin/gcm/$', 'gestorpsi.gcm.views.views.org_object_list', name='gcm-index'),

    # include
    (r'^accounts/', include('gestorpsi.authentication.urls')),
    (r'^accounts/', include('registration.urls')), # logout
    (r'^admin/', include(admin.site.urls)),
    (r'^contact/', include('gestorpsi.contact.urls')),
    (r'^place/', include('gestorpsi.place.urls')),
    (r'^careprofessional/', include('gestorpsi.careprofessional.urls')),
    (r'^client/', include('gestorpsi.client.urls')),
    (r'^client/', include('gestorpsi.demographic.urls')),
    (r'^client/', include('gestorpsi.ehr.urls')),
    #(r'^client/', include('gestorpsi.socioeconomic.urls')),
    (r'^admission/', include('gestorpsi.admission.urls')),
    (r'^referral/', include('gestorpsi.referral.urls')),
    (r'^employee/', include('gestorpsi.employee.urls')),
    (r'^person/', include('gestorpsi.person.urls')),
    (r'^address/', include('gestorpsi.address.urls')),
    (r'^service/', include('gestorpsi.service.urls')),
    (r'^device/', include('gestorpsi.device.urls')),
    (r'^organization/', include('gestorpsi.organization.urls')),
    (r'^upload/', include('gestorpsi.upload.urls')),
    (r'^user/', include('gestorpsi.users.urls')),
    (r'^schedule/', include('gestorpsi.schedule.urls')),
    (r'^report/', include('gestorpsi.report.urls')),
    (r'^support/', include('gestorpsi.support.urls')),
    (r'^frontend/', include('gestorpsi.frontend.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'^profile/', include('gestorpsi.profile.urls')),
    (r'^util/', include('gestorpsi.util.urls')),
    (r'^chaining/', include('smart_selects.urls')),
    (r'^sentry/', include('sentry.web.urls')),
    (r'^gcm/', include('gestorpsi.gcm.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

gestorpsi/util/urls.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from gestorpsi.util.views import cnae, ocupation

urlpatterns = patterns('',
    (r'^cnae/$', login_required(cnae)), 
    (r'^ocupation/$', login_required(ocupation)), 
)

gestorpsi/address/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

import reversion
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from gestorpsi.util.uuid_field import UuidField

class Country(models.Model):
    name = models.CharField(max_length=50)
    nationality = models.CharField(max_length=50)
    def __unicode__(self):
        return u"%s" % self.name
    class Meta:
        ordering = ['name']

class State(models.Model):
    name = models.CharField(max_length=50)
    shortName = models.CharField(max_length=2)
    country = models.ForeignKey(Country)
    def __unicode__(self):
        return u"%s" % self.name
    class Meta:
        ordering = ['name']

class City(models.Model):
    ibge_code = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    state = models.ForeignKey(State)
    def __unicode__(self):
        return u"%s" % (self.name)
    class Meta:
        ordering = ['name']

class AddressType(models.Model):
    description = models.CharField(max_length=20)
    weight = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return u"%s" % self.description

    class Meta:
        ordering = ['weight']

class Address(models.Model):
    # Brazil Address
    id= UuidField( primary_key= True )
    addressPrefix = models.CharField(max_length=10)
    addressLine1 = models.CharField(max_length=50, blank=True)
    addressLine2 = models.CharField(max_length=50, blank=True)
    addressNumber = models.CharField(max_length=10, blank=True)
    neighborhood = models.CharField(max_length=30, blank=True)
    zipCode = models.CharField(max_length=10, blank=True)
    addressType = models.ForeignKey(AddressType)
    city = models.ForeignKey(City, null=True)
    # Foreign Address
    foreignCountry = models.ForeignKey(Country, null=True)
    foreignState   = models.CharField(max_length=20, blank=True)
    foreignCity    = models.CharField(max_length=50, blank=True)
    # Generic Relationship
    content_type = models.ForeignKey(ContentType)
    object_id = models.CharField(max_length=36)
    content_object = generic.GenericForeignKey()
    
    def __cmp__(self, other):
        if (self.addressPrefix == other.addressPrefix) and \
           (self.addressLine1 == other.addressLine1) and \
           (self.addressLine2 == other.addressLine2) and \
           (self.addressNumber == other.addressNumber) and \
           (self.neighborhood == other.neighborhood) and \
           (self.zipCode == other.zipCode) and \
           (self.addressType == other.addressType) and \
           (self.city == other.city) and \
           (self.foreignCountry == other.foreignCountry) and \
           (self.foreignState == other.foreignState) and \
           (self.foreignCity == other.foreignCity):
            return 0
        else:
            return 1    
    
    def __unicode__(self):
        return u"%s %s %s %s<br />%s %s %s %s %s (%s)" % (\
            self.addressPrefix, self.addressLine1, self.addressNumber, self.addressLine2, \
            self.zipCode, self.neighborhood, self.city, '' if not hasattr(self.city, 'state') else self.city.state.shortName, '' if not hasattr(self.city, 'state') else self.city.state.country, self.addressType\
        )
    
    def __empty__(self):
        return ''
    area = property(__empty__)

    def revision(self):
        return reversion.get_for_object(self).order_by('-revision__date_created').latest('revision__date_created').revision

reversion.register(Address)

gestorpsi/cbo/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.db import models

class Occupation(models.Model):
    """
    This class represents an occupation according to http://www.mte.gov.br
    @author: GestorPsi
    @version: 1.0
    """
    id = models.IntegerField(primary_key=True)
    cbo_code = models.CharField(max_length=999)
    title = models.CharField(max_length=999)

    def __unicode__(self):
        return u"%s" % self.title

class Synonyms(models.Model):
    """
    This class represents a synonyms that refers to an occupation
    @author: GestorPsi
    @version: 1.0
    """
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=999)
    occupation = models.ForeignKey(Occupation)

    def __unicode__(self):
        return u"%s" % self.title

gestorpsi/device/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

import reversion
from django.db import models
from django.utils.translation import ugettext as _
from gestorpsi.organization.models import Organization
from gestorpsi.place.models import Place, Room
from gestorpsi.careprofessional.models import Profession
from gestorpsi.util.uuid_field import UuidField

DURABILITY_TYPE= ( ('1',_('CONSUMABLE')), ('2', _('DURABLE')) )
"""
Devices are classified by their durability, thus this variable represents
the two kinds of durability type that are used to classify them.
"""

MOBILITY_TYPE= ( ( '1', _('FIX') ), ( '2', _('MOBILE') ) )
"""
Similarly, devices are also classified by their mobility, thus this variable represents
the two kinds of mobility type that are used to classify them.
"""

class DeviceDetailsManager(models.Manager):
    def mobile(self):
        return super(DeviceDetailsManager, self).get_query_set().filter(mobility__exact='2')

    def fix(self):
        return super(DeviceDetailsManager, self).get_query_set().filter(mobility__exact='1')

    def active(self, organization):
        return super(DeviceDetailsManager, self).get_query_set().filter(active = True, device__organization = organization).order_by('model')

    def deactive(self, organization):
        return super(DeviceDetailsManager, self).get_query_set().filter(active = False, device__organization = organization).order_by('model')

class Device(models.Model):
    """
    The class C{Device} is used to represent devices in the context of the GestorPsi project. Using this class,
    the user is able to query the quantity of some kind of device currently available as well as the number of existing
    devices of the underlying type.
    @version: 1.0
    """
    id = UuidField(primary_key=True)
    description = models.CharField( max_length = 80 )
    organization = models.ForeignKey(Organization, null=True)

    def get_all_device_details(self):
        return DeviceDetails.objects.filter( device__id= self.id )

    def __unicode__(self):
       return u"%s" % ( self.description )

    def revision(self):
        return reversion.get_for_object(self).order_by('-revision__date_created').latest('revision__date_created').revision

    class Meta:
        ordering = ['description']
        permissions = (
            ("device_add", "Can add devices"),
            ("device_change", "Can change devices"),
            ("device_list", "Can list devices"),
            ("device_write", "Can write devices"),
        )



class DeviceDetails(models.Model):
    """
    Instances of this class holds details about devices. For example, brand, comments, and so forth.
    @version: 1.0
    @see: Device
    """
    id = UuidField(primary_key=True)
    brand = models.CharField( max_length=80 )
    model = models.CharField( max_length=80 )
    part_number = models.CharField( max_length=45 )
    lendable = models.BooleanField( default=True )
    comments = models.CharField( max_length=200 )
    durability = models.CharField( max_length=1, choices=DURABILITY_TYPE )
    prof_restriction = models.ForeignKey(Profession, null=True)
    mobility = models.CharField( max_length=1, choices=MOBILITY_TYPE )
    place = models.ForeignKey(Place, null=True)
    room = models.ForeignKey(Room, null=True)
    device = models.ForeignKey(Device)
    active = models.BooleanField(default=True)

    objects = DeviceDetailsManager()

    class Meta:
        ordering = ['brand']
        permissions = (
            ("devicedetails_write", "Can write device details"),
        )

    def __unicode__(self):
        device_type = _("Type")
        device_model = _("Model")
        device_part_number = _("Part number")
        return u"%s: %s - %s: %s - %s: %s" % \
                 (device_type, self.device.description, device_model, self.model, device_part_number, self.part_number)

    def revision(self):
        return reversion.get_for_object(self).order_by('-revision__date_created').latest('revision__date_created').revision

reversion.register(DeviceDetails, follow=['device'])
reversion.register(Device)

gestorpsi/templates/tags/schedule_form.html
{% comment %}

Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

{% endcomment %}

{% load i18n %}

<script type="text/javascript" src="/media/js/gestorpsi.schedule.js"></script>
<div class="schedule">
    <div id="form">

    <h2 class="title_schedule title">{% trans "Adding New Event" %}</h2>
    <p class="description">{% trans "Inform the schedule details then click on Save button" %}</p>

    <form method="post" action="" class="schedule refresh">
    <input type="hidden" name="tabtitle" class="tabtitle" />
    <input type="hidden" name="day_month" id="id_day_month" value="{{  dtstart|date:"n" }}" />
    <input type="hidden" name="day_day" id="id_day_day" value="{{ dtstart|date:"j" }}" />
    <input type="hidden" name="day_year" id="id_day_year" value="{{ dtstart|date:"Y" }}" />
    <input type="hidden" name="room" id="id_room" value="{{ room_id }}" />

    <div class="main_area">
    {{ event_form.errors }}
    {{ recurrence_form.errors }}
        <a href="" id="help">&nbsp;</a>
            <fieldset>
            <legend>{% trans "Schedule Due" %}</legend>
            <h2 class="red">
            {{ dtstart|date:"l," }} {{ dtstart|date:"d" }} {% trans "of" %} {{ dtstart|date:"F" }} {% trans "of" %} {{ dtstart|date:"Y" }} - {{ room }} <a href="/schedule/"><small>[{% trans "change" %}]</small></a>
            </h2>
                <label>{% trans "Start Time" %}<br />
                {{ recurrence_form.start_time_delta }}
                </label>
                <label>{% trans "End Time" %}<br />
                {{ recurrence_form.end_time_delta }}
                </label>

                <div style="clear:both"></div>
                <label class="event_is_online">{% trans "Is online" %}</label>
                <div class="event_is_online">
                {{ recurrence_form.is_online }}
                </div>
            </fieldset>

            {% if not referral %} {# schedule view #}
            <fieldset class="existing_referral" id="existing_referral_true">
            <legend>{% trans "Existing Referral" %}</legend>

                    <div>
                    <label style="margin-left: 0px !important;">{% trans "Client" %}*<br />
                    <div id="fb_client"></div> <!-- clients from organization -->
                    </label>
                    </div>
                    <div class="hidden client_referrals" style="margin-left: 0px !important;">
                    <label>{% trans "Service" %}*<br />
                    <select name="referral" class="big">
                    </select>
                    </label>
                    </div>
                    <div style="clear:both"><br />
                    <a style="cursor:pointer;" onclick="$('fieldset#existing_referral_true').hide();$('fieldset.referral_group').show('slow'); ">{% trans "Schedule a Group?" %}</a>

                    <br>
                    <br>
                    <a style="cursor:pointer;" onclick="$('fieldset#existing_referral_true').hide();$('fieldset.referral_service').show('slow'); ">Reservar Sala</a>

                    </div>
            </fieldset>
            {% else %} {# client schedule view #}
                <input type="hidden" name="referral" value="{{ referral.id }}" />
            {% endif %}

            <fieldset class="referral_group hidden">
            <legend>{% trans "Group" %}*</legend>
                <label>{% trans "Choice one group or" %} <a href="/service/">{% trans "add a new one" %}</a> {% trans "from selected service" %}<br />
                    <select name="group" class="giant">
                    <option value="">--------</option>
                    {% for i in group %}
                        <option value="{{ i.id }}"{% if not i.charged_members %} disabled{% endif %}>{{ i.service.name }} - {{ i }}{% if not i.charged_members %} ({% trans "Empty" %}){% endif %}</option>
                    {% endfor %}
                    </select>
                </label>
                <div style="clear:both"><br />
                    <a style="cursor:pointer;" onclick="$('fieldset.referral_group').hide();$('fieldset.existing_referral').show('slow');$('fieldset.referral_group select option:first').attr('selected', 'selected');">{% trans "Schedule a single client?" %}</a>

                    <br>
                    <br>
                    <a style="cursor:pointer;" onclick="$('fieldset.referral_group').hide();$('fieldset#existing_referral_true').hide();$('fieldset.referral_service').show('slow'); ">Reservar Sala</a>

                </div>
            </fieldset>

            <fieldset class="referral_service hidden">
            <br>
            <legend>{% trans "Service" %}</legend>
                <div class="referral_services" style="margin-left: 0px !important;">
                    <label>{% trans "Service" %}<br />
                        <select name="select_referral" class="select asm" style="min-width:400px;">
                            {% for l in referrals %}
                                <option value="{{ l.id }}"{% ifequal object.referral.id l.id %} selected{% endifequal %}>{{ l.service.name }}</option>
                            {% endfor %}
                        </select>
                    </label>
                    <div style="clear:both"><br />
                        <a style="cursor:pointer;" onclick="$('fieldset.referral_service').hide();$('fieldset.existing_referral').show('slow');">{% trans "Schedule a single client?" %}</a>

                        <br>
                        <br>
                        <a style="cursor:pointer;" onclick="$('fieldset.referral_service').hide();$('fieldset.referral_group').show('slow'); ">{% trans "Schedule a Group?" %}</a>
                    </div>
                </div>
            </fieldset>

			<fieldset>
				<legend>{% trans "Professional Details" %}</legend>
		            <div style="clear:both;"></div>
		            <label>{% trans "Professionals" %}<br />
		                <div class="overflow referral_form_professional {% if not referral.id %} hide_on_first{% endif %}">
                            {{recurrence_form.professionals}}
		                </div>
		            </label>

		        <label style="display:none">{% trans "Clients" %}<br />
		        {{ referral_form.client }}
		        </label>
			</fieldset>

            <fieldset>
            <legend>{% trans "Schedule Details" %}</legend>
                <label>{% trans "Notes" %}<br />
                <textarea name="annotation" class="giant" rows="10"></textarea>
                </label>
                <label>{% trans "Devices" %}<br /></label>
                <div class="overflow">
                    {{ recurrence_form.device }}
                </div>
            </fieldset>

            <fieldset>
            <legend>{% trans "Occurrence Details" %}</legend>
                <label>{% trans "Occurrence Format" %}</label>
                <div class="switch" clean="occurrence_repeat">
                {{ recurrence_form.repeats }}
                </div>
                <div style="clear:both;"></div>
                <label class="occurrence_repeat occurrence_repeat_count">{% trans "Total Occurrences" %} <small>({% trans "Limited about 40 occurrences for each submit" %})</small><br />
                {{ recurrence_form.count }}
                </label>
                <label class="occurrence_repeat occurrence_repeat_until hidden">{% trans "End Time" %}</label>
                <div class="occurrence_repeat occurrence_repeat_until hidden">
                {{ recurrence_form.until }}
                </div>
            </fieldset>

            <fieldset>
            <legend>{% trans "Occurrence Frequency" %}</legend>
                <label>{% trans "Frequency Period" %}</label>
                <div class="switch" clean="occurrence_freq">
                {{ recurrence_form.freq }}
                <script>
                    $(function() { $('label[for=id_freq_3]').hide() });
                </script>
                </div>
                <div style="clear:both;"></div>
                <label>{% trans "Interval" %}<br />
                {{ recurrence_form.interval }}
                </label>
            </fieldset>

            <fieldset class="occurrence_freq occurrence_freq_2">
            <legend>{% trans "Weekly Options" %}</legend>
                <label>{% trans "Days of the week" %}<br />
                {{ recurrence_form.week_days }}
                </label>
            </fieldset>

            <fieldset class="occurrence_freq occurrence_freq_1 hidden">
            <legend>{% trans "Monthly options" %}</legend>
                <label>{% trans "Repeat" %}</label>
                <div class="switch" clean="occurrence_monthly">
                {{ recurrence_form.month_option }}
                </div>
                <div style="clear: both;"></div>
                <label class="occurrence_monthly occurrence_monthly_on hidden">{% trans "Month ordinal" %}<br />
                {{ recurrence_form.month_ordinal }}
                </label>
                <label class="occurrence_monthly occurrence_monthly_on hidden">{% trans "Month ordinal day" %}<br />
                {{ recurrence_form.month_ordinal_day }}
                </label>
                <div class="occurrence_monthly occurrence_monthly_each">
                <label>{% trans "Event repeat on these days of the month" %}

                </label>
                {{ recurrence_form.each_month_day }}
                </div>
            </fieldset>


            <fieldset class="occurrence_freq occurrence_freq_0 hidden">
            <legend>{% trans "Yearly options" %}</legend>
                <label>{% trans "Event repeat on these months of year" %}<br />
                {{ recurrence_form.year_months }}
                </label>
                <label>{% trans "Is year month ordinal" %}</label>
                <div class="switch" clean="is_year_month_ordinal">
                {{ recurrence_form.is_year_month_ordinal }}
                </div>
                <label class="is_year_month_ordinal hidden">{% trans "Year month ordinal" %}<br />
                {{ recurrence_form.year_month_ordinal }}
                </label>
                <label class="is_year_month_ordinal hidden">{% trans "Year month ordinal day" %}<br />
                {{ recurrence_form.year_month_ordinal_day }}
                </label>
            </fieldset>
    <div style="clear:both;"></div>
    <br />
      </div>

    <div id="sidebar" class="sidebar">
            <div class="bg_blue">
                {% include "tags/save.html" %}
            </div>
    </div>

    </form>

    <div id="schedule_occurrence_list">
        {% include "schedule/schedule_occurrence_list.html" %}
    </div>

    </div>
</div>