gestorpsi/ehr/urls.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from gestorpsi.authentication.views import login_check
from gestorpsi.ehr.views import *

urlpatterns = patterns('',
    # Session's URL
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/$', login_check(session_list)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/(?P<session_id>\d+)/item/$', login_check(session_item_html)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/add/$', login_check(session_form)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/session/(?P<session_id>\d+)/$', login_check(session_form)),

    # Diagnosis's URL
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/$', login_check(diagnosis_list)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/(?P<diagnosis_id>\d+)/item/$', login_check(diagnosis_item_html)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/add/$', login_check(diagnosis_form)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/diagnosis/(?P<diagnosis_id>\d+)/$', login_check(diagnosis_form)),
    
    # Demand's URL
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/$', login_check(demand_list)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/(?P<demand_id>\d+)/item/$', login_check(demand_item_html)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/add/$', login_check(demand_form)),
    (r'^(?P<client_id>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/(?P<referral_id>\d+)/demand/(?P<demand_id>\d+)/$', login_check(demand_form)),
)

gestorpsi/gcm/urls.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.conf.urls.defaults import url, patterns
from django.views.generic.simple import direct_to_template
from django.contrib.auth.decorators import login_required

from gestorpsi.gcm.views.views import org_object_list

urlpatterns = patterns('',
    # use by admin section
    url(r'^$', login_required( direct_to_template ), {'template':'gcm/index.html'}, name='gcm-index'),
    url(r'gcm/org/$', login_required( org_object_list ), name='org-list'),
)

gestorpsi/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
#from gestorpsi.authentication.forms import RegistrationForm
from gestorpsi.authentication.models import Profile
from gestorpsi.frontend.views import start as frontend_start
from django.contrib.auth.decorators import login_required
from gestorpsi.authentication.views import gestorpsi_login

from gestorpsi.settings import MEDIA_ROOT

admin.autodiscover()

urlpatterns = patterns('',
    # url
    (r'^$', login_required(frontend_start)),
    url(r'^accounts/login/$', 'gestorpsi.authentication.views.gestorpsi_login', {'template_name': 'registration/login.html'}, name='auth_login'),

    # registration org form
    url(r'^accounts/register/$', 'gestorpsi.authentication.views.register', name='registration-register'),
    url(r'^accounts/complete/$', 'gestorpsi.authentication.views.complete', name='registration-complete'),

    # user custom admin for GCM
    url(r'^admin/gcm/$', 'gestorpsi.gcm.views.views.org_object_list', name='gcm-index'),

    # include
    (r'^accounts/', include('gestorpsi.authentication.urls')),
    (r'^accounts/', include('registration.urls')), # logout
    (r'^admin/', include(admin.site.urls)),
    (r'^contact/', include('gestorpsi.contact.urls')),
    (r'^place/', include('gestorpsi.place.urls')),
    (r'^careprofessional/', include('gestorpsi.careprofessional.urls')),
    (r'^client/', include('gestorpsi.client.urls')),
    (r'^client/', include('gestorpsi.demographic.urls')),
    (r'^client/', include('gestorpsi.ehr.urls')),
    #(r'^client/', include('gestorpsi.socioeconomic.urls')),
    (r'^admission/', include('gestorpsi.admission.urls')),
    (r'^referral/', include('gestorpsi.referral.urls')),
    (r'^employee/', include('gestorpsi.employee.urls')),
    (r'^person/', include('gestorpsi.person.urls')),
    (r'^address/', include('gestorpsi.address.urls')),
    (r'^service/', include('gestorpsi.service.urls')),
    (r'^device/', include('gestorpsi.device.urls')),
    (r'^organization/', include('gestorpsi.organization.urls')),
    (r'^upload/', include('gestorpsi.upload.urls')),
    (r'^user/', include('gestorpsi.users.urls')),
    (r'^schedule/', include('gestorpsi.schedule.urls')),
    (r'^report/', include('gestorpsi.report.urls')),
    (r'^support/', include('gestorpsi.support.urls')),
    (r'^frontend/', include('gestorpsi.frontend.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'^profile/', include('gestorpsi.profile.urls')),
    (r'^util/', include('gestorpsi.util.urls')),
    (r'^chaining/', include('smart_selects.urls')),
    (r'^sentry/', include('sentry.web.urls')),
    (r'^gcm/', include('gestorpsi.gcm.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

gestorpsi/util/urls.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from gestorpsi.util.views import cnae, ocupation

urlpatterns = patterns('',
    (r'^cnae/$', login_required(cnae)), 
    (r'^ocupation/$', login_required(ocupation)), 
)

gestorpsi/address/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

import reversion
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from gestorpsi.util.uuid_field import UuidField

class Country(models.Model):
    name = models.CharField(max_length=50)
    nationality = models.CharField(max_length=50)
    def __unicode__(self):
        return u"%s" % self.name
    class Meta:
        ordering = ['name']

class State(models.Model):
    name = models.CharField(max_length=50)
    shortName = models.CharField(max_length=2)
    country = models.ForeignKey(Country)
    def __unicode__(self):
        return u"%s" % self.name
    class Meta:
        ordering = ['name']

class City(models.Model):
    ibge_code = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    state = models.ForeignKey(State)
    def __unicode__(self):
        return u"%s" % (self.name)
    class Meta:
        ordering = ['name']

class AddressType(models.Model):
    description = models.CharField(max_length=20)
    weight = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return u"%s" % self.description

    class Meta:
        ordering = ['weight']

class Address(models.Model):
    # Brazil Address
    id= UuidField( primary_key= True )
    addressPrefix = models.CharField(max_length=10)
    addressLine1 = models.CharField(max_length=50, blank=True)
    addressLine2 = models.CharField(max_length=50, blank=True)
    addressNumber = models.CharField(max_length=10, blank=True)
    neighborhood = models.CharField(max_length=30, blank=True)
    zipCode = models.CharField(max_length=10, blank=True)
    addressType = models.ForeignKey(AddressType)
    city = models.ForeignKey(City, null=True)
    # Foreign Address
    foreignCountry = models.ForeignKey(Country, null=True)
    foreignState   = models.CharField(max_length=20, blank=True)
    foreignCity    = models.CharField(max_length=50, blank=True)
    # Generic Relationship
    content_type = models.ForeignKey(ContentType)
    object_id = models.CharField(max_length=36)
    content_object = generic.GenericForeignKey()
    
    def __cmp__(self, other):
        if (self.addressPrefix == other.addressPrefix) and \
           (self.addressLine1 == other.addressLine1) and \
           (self.addressLine2 == other.addressLine2) and \
           (self.addressNumber == other.addressNumber) and \
           (self.neighborhood == other.neighborhood) and \
           (self.zipCode == other.zipCode) and \
           (self.addressType == other.addressType) and \
           (self.city == other.city) and \
           (self.foreignCountry == other.foreignCountry) and \
           (self.foreignState == other.foreignState) and \
           (self.foreignCity == other.foreignCity):
            return 0
        else:
            return 1    
    
    def __unicode__(self):
        return u"%s %s %s %s<br />%s %s %s %s %s (%s)" % (\
            self.addressPrefix, self.addressLine1, self.addressNumber, self.addressLine2, \
            self.zipCode, self.neighborhood, self.city, '' if not hasattr(self.city, 'state') else self.city.state.shortName, '' if not hasattr(self.city, 'state') else self.city.state.country, self.addressType\
        )
    
    def __empty__(self):
        return ''
    area = property(__empty__)

    def revision(self):
        return reversion.get_for_object(self).order_by('-revision__date_created').latest('revision__date_created').revision

reversion.register(Address)

gestorpsi/authentication/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.db import models
from django.contrib.auth.models import User, UserManager, Group
from gestorpsi.organization.models import Organization
from gestorpsi.person.models import Person
from gestorpsi.util import CryptographicUtils as cryptoUtils
from gestorpsi.util.uuid_field import UuidField


class Profile(models.Model):
    user = models.OneToOneField(User, unique=True)
    # organization = models.ManyToManyField(Organization, null=True)
    organization = models.ManyToManyField(
        Organization, through='Role', null=True)
    try_login = models.IntegerField(default=0, null=True)
    crypt_temp = models.CharField(max_length=256, blank=True, null=True)
    org_active = models.ForeignKey(
        Organization, related_name="org_active", null=True)
    person = models.OneToOneField(Person, null=True)

    objects = UserManager()

    def __unicode__(self):
        return u"%s" % self.user.username

    def _set_temp(self, value):
        self.crypt_temp = cryptoUtils.encrypt_attrib(value)

    def _get_temp(self):
        return cryptoUtils.decrypt_attrib(self.crypt_temp)

    temp = property(_get_temp, _set_temp)


class Role(models.Model):
    profile = models.ForeignKey(Profile)
    organization = models.ForeignKey(Organization)
    group = models.ForeignKey(Group)

    def __unicode__(self):
        return u"%s | %s | %s" % (self.profile, self.organization, self.group)

gestorpsi/cbo/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

from django.db import models

class Occupation(models.Model):
    """
    This class represents an occupation according to http://www.mte.gov.br
    @author: GestorPsi
    @version: 1.0
    """
    id = models.IntegerField(primary_key=True)
    cbo_code = models.CharField(max_length=999)
    title = models.CharField(max_length=999)

    def __unicode__(self):
        return u"%s" % self.title

class Synonyms(models.Model):
    """
    This class represents a synonyms that refers to an occupation
    @author: GestorPsi
    @version: 1.0
    """
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=999)
    occupation = models.ForeignKey(Occupation)

    def __unicode__(self):
        return u"%s" % self.title

gestorpsi/employee/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""

import reversion
from django.db import models
from gestorpsi.person.models import Person
from gestorpsi.util.uuid_field import UuidField

class EmployeeManager(models.Manager):
    def active(self, organization):
        return super(EmployeeManager, self).get_query_set().filter(active=True, person__organization = organization).order_by('person__name')
    def deactive(self, organization):
        return super(EmployeeManager, self).get_query_set().filter(active=False, person__organization = organization).order_by('person__name')

class Employee(models.Model):
    id = UuidField(primary_key=True)
    person = models.OneToOneField(Person)
    hiredate = models.DateField(blank=True, null=True)
    job = models.CharField(max_length=30, blank=True)
    active = models.BooleanField(default=True)
    objects = EmployeeManager()
    
    def __unicode__(self):
        return u"%s" % self.person.name

    class Meta:
        ordering = ['person']
        permissions = (
            ("employee_add", "Can add employees"),
            ("employee_change", "Can change employees"),
            ("employee_list", "Can list employees"),
            ("employee_write", "Can write employees"),
        )

    def revision(self):
        return reversion.get_for_object(self).order_by('-revision__date_created').latest('revision__date_created').revision

reversion.register(Employee)

gestorpsi/frontend/models.py
# -*- coding: utf-8 -*-

"""
Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
"""


# Create your models here.

gestorpsi/templates/employee/employee_form.html
{% extends "core/main.html" %}

{% comment %}

Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

{% endcomment %}

{% load i18n %}

{% block menu_myoffice %}active{% endblock %}

{% block vertical_menu %} - {% trans "Employees" %}{% endblock %}

{% block submenu %}
    <ul>
        <li><a class="first" href="/employee/">{% trans "all" %}</a></li>
        {% if perms.employee.employee_write %}
            <li><a class="{% if not object.id %}active{% endif %}" href="/employee/add/">{% trans "add" %}</a></li>
        {% endif %}
        <li><a href="/employee/deactive/">{% trans "Deactives" %}</a></li>
        {% if object.id %}<li><a class="active">{{ object.person.name }}</a></li>{% endif %}
        
    </ul>
{% endblock %}

{% block core %}

<h2 id="title_addressbook" style="display:none"></h2>

{% if object.id %}
	<h2 class="title_employee title">{{ object.person.name }}</h2>
{% else %}
	<h2 class="title_employee title">{% trans "Adding New Employee" %}</h2>
	<p class="description">{% trans "Inform the employee details then click on Save button" %}</p>
{% endif %}


</p>
<h2 id="title_contacts" style="display:none"></h2>
<h2 id="title_myoffice" style="display:none"></h2>


<form action="/employee/{% if object.id %}{{ object.id }}/{% endif %}save/" method="post" id="form_employee" class="form_people collapsable form_employee">	
<div class="main_area">

	<!-- <a href="" id="help">&nbsp;</a> -->
	<!-- DataTypes form menu -->
	
	
	{% include "meta/people_indentification.html" %}
	
	<!--
	Employee infos
	-->
	
	<fieldset id="fieldset_employee_details">
		<legend>{% trans "Professional Identification" %}</legend>
			<label>{% trans "Job" %}<br />
			<input type="text" maxlength="30" name="job" class="big" value="{{ object.job }}" id="id_job" />
			</label>
			<label>{% trans "Hiredate" %}<br />
			<input type="text" name="hiredate" class="calendar birthdate" value="{% ifnotequal object.hiredate None %}{{ object.hiredate|date:"d/m/Y" }}{% endifnotequal %}" id="id_hiredate" mask="99/99/9999" />
			</label>
	</fieldset>

	{% include "meta/people_profile.html" %}
	{% include "meta/addressbook.html" %}
	{% include "meta/internet.html" %}

<fieldset class="comment_form">
        <legend>{% trans "Comments" %}</legend>
        <label>
                <textarea name="comments" class="extrabig">{{ object.person.comments }}</textarea>
        </label>

</fieldset>


<br />	
</div>

{% include "tags/employee_sidebar.html" %}

</form>

{% include "tags/upload.html" %}

{% endblock %}

gestorpsi/templates/employee/employee_list.html
{% extends "core/main.html" %}

{% comment %}

Copyright (C) 2008 GestorPsi

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

{% endcomment %}

{% load i18n %}

{% block menu_myoffice %}active{% endblock %}

{% block vertical_menu %} - {% trans "Employees" %}{% endblock %}

{% block submenu %}
    <ul>
        <li><a class="first {% if not deactive %} active {% endif %}" href="/employee/">{% trans "all" %}</a></li>
        {% if perms.employee.employee_write %}
            <li><a href="/employee/add/">{% trans "add" %}</a></li>
        {% endif %}
        <li><a class="{% if deactive %} active {% endif %}" href="/employee/deactive/">{% trans "Deactives" %}</a></li>
    </ul>
{% endblock %}

{% block core %}

<div class="registers_available">
        <h2 id="title_addressbook" style="display: none"></h2>
        <h2 id="title_clients" style="display: none"></h2>
       
        {% if deactive %} 
            <h2 class="title_employee">{% trans "All Employees Deactive" %}</h2>
        {% else %}
            <h2 class="title_employee">{% trans "All Employees" %}</h2>
        {% endif %}
        <p class="description">{% trans "Displaying" %} <a href="/employee/" display="list"><span id="object_length"></span> {% trans "employees(s)" %}</a>. {% trans "Page" %} <b></b> {% trans "of" %} <b></b></p>
        <h2 id="title_myoffice" style="display: none"></h2>
        
        <div class="main_area contact">
            <div id="search_header" class="employee_search {% if deactive %} deactive {% else %} active {% endif %}">
                {% include "tags/search_header.html" %}
            </div>

        <div id="msg_area" class="alert no_registers_available hidden">
            {% trans "There is no registers available." %}<br />
            {% if perms.employee.employee_write %}
                <br />{% trans "Click" %} <a href="/employee/add/" display="form" class="fastmenu notajax" sub_menu="sub_employees">{% trans "here" %}</a> {% trans "if you want to add a new one." %}
            {% endif %}
        </div>

        <table id="search_results" class="zebra newtab" border="0" cellspacing="0" cellpadding="0">
                <thead> 
                        <tr> 
                        <th></th> 
                        <th></th> 
                        </tr> 
                </thead>
                <tbody>
                    <script>
                        {% if deactive %}
                            updateEmployee('/employee/page1/deactive/', true);
                        {% else %}
                            updateEmployee('/employee/page1/');
                        {% endif %}
                    </script>
                </tbody>
                </table>
                {% include "tags/paginator.html"%}
        </div>
</div>
{% endblock %}